version: '3'

services:
  app:
    build:
      context: ./
    container_name: habits-bot
    command: npm run start
    restart: unless-stopped
    ports:
      - '4000:4000'
    env_file:
      - .env.production
